
package com.senneko.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SumaPort", targetNamespace = "http://main.ws.senneko.com/", wsdlLocation = "file:/C:/Users/senneko/AppData/Local/Temp/tempdir2858735831561476095.tmp/SumaPort_1.wsdl")
public class SumaPort_Service
    extends Service
{

    private final static URL SUMAPORT_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.senneko.ws.client.SumaPort_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.senneko.ws.client.SumaPort_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/senneko/AppData/Local/Temp/tempdir2858735831561476095.tmp/SumaPort_1.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/senneko/AppData/Local/Temp/tempdir2858735831561476095.tmp/SumaPort_1.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SUMAPORT_WSDL_LOCATION = url;
    }

    public SumaPort_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SumaPort_Service() {
        super(SUMAPORT_WSDL_LOCATION, new QName("http://main.ws.senneko.com/", "SumaPort"));
    }

    /**
     * 
     * @return
     *     returns SumaPort
     */
    @WebEndpoint(name = "SumaPortPort")
    public SumaPort getSumaPortPort() {
        return super.getPort(new QName("http://main.ws.senneko.com/", "SumaPortPort"), SumaPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SumaPort
     */
    @WebEndpoint(name = "SumaPortPort")
    public SumaPort getSumaPortPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://main.ws.senneko.com/", "SumaPortPort"), SumaPort.class, features);
    }

}
